version: '3'

services:
  kemono-games-search:
    image: registry-vpc.cn-guangzhou.aliyuncs.com/kemono/bloodhound:{{GIT-SHA}}
    restart: always
    deploy:
      resources:
        limits:
          memory: 500M
    ports:
      - 8120:3000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - PORT=3000
      - LOG_FORMAT=combined
      - LOG_DIR=../logs
      - ORIGIN=*
      - CREDENTIALS=true
      - ELASTIC_SEARCH_ENDPOINT=http://172.27.144.230:9001/
    volumes:
      - ./logs:/app/logs
