version: '3'

services:
  kemono-games-search:
    image: registry.ap-northeast-1.aliyuncs.com/kemono/bloodhound:{{GIT-SHA}}
    restart: always
    deploy:
      resources:
        limits:
          memory: 500M
    ports:
      - 8120-8123:3000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - PORT=3000
      - LOG_FORMAT = combined
      - LOG_DIR = ../logs
      - ORIGIN = *
      - CREDENTIALS = true
      - ELASTIC_SEARCH_ENDPOINT=http://10.0.0.101:9200/
