name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true
    runs-on: [self-hosted, Intel]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          docker build -t registry.ap-northeast-1.aliyuncs.com/kemono/bloodhound:${GIT_HASH} .

  push:
    needs: [build]
    runs-on: [self-hosted, Intel]
    steps:
      - name: Push Image
        run: |
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          docker push registry.ap-northeast-1.aliyuncs.com/kemono/bloodhound:${GIT_HASH}
          docker tag registry.ap-northeast-1.aliyuncs.com/kemono/bloodhound:${GIT_HASH} registry.cn-guangzhou.aliyuncs.com/kemono/bloodhound:${GIT_HASH}
          docker push registry.cn-guangzhou.aliyuncs.com/kemono/bloodhound:${GIT_HASH}

  deploy:
    needs: [push]
    runs-on: [self-hosted, docker]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Global
        run: |
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          mkdir -p /home/ubuntu/kemono-games-search
          cp docker-compose.sample.yml /home/ubuntu/kemono-games-search/docker-compose.yml
          cd /home/ubuntu/kemono-games-search
          sed -i "s/{{GIT-SHA}}/${GIT_HASH}/g" docker-compose.yml
          docker-compose up -d
      - name: Deploy CN
        run: |
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          scp docker-compose.sample.yml /tmp/docker-compose.yml
          sed -i "s/{{GIT-SHA}}/${GIT_HASH}/g" /tmp/docker-compose.yml
          scp /tmp/docker-compose.yml web02:/root/kemono-games-search/
          ssh web02 "cd /root/kemono-games-search && docker compose up -d"
