name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true
    runs-on: [self-hosted, Intel]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          docker build -t registry.ap-northeast-1.aliyuncs.com/kemono/bloodhound:${GIT_HASH} .

  push:
    needs: [build]
    runs-on: [self-hosted, Intel]
    steps:
      - name: Push Image
        run: |
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          docker push registry.ap-northeast-1.aliyuncs.com/kemono/bloodhound:${GIT_HASH}
          docker tag registry.ap-northeast-1.aliyuncs.com/kemono/bloodhound:${GIT_HASH} registry.cn-guangzhou.aliyuncs.com/kemono/bloodhound:${GIT_HASH}
          docker push registry.cn-guangzhou.aliyuncs.com/kemono/bloodhound:${GIT_HASH}

  deploy:
    needs: [push]
    runs-on: [self-hosted, docker]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Global
        run: |
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          mkdir -p /tmp/kemono-games-search-global
          cp docker-compose.sample.yml /tmp/kemono-games-search-global/docker-compose.yml
          sed -i "s/{{GIT-SHA}}/${GIT_HASH}/g" /tmp/kemono-games-search-global/docker-compose.yml
          
          SERVER=("web01" "web02" "db")
          parallel ssh {}.jp.internal.abo.network "mkdir -p /root/kemono-games-search" ::: ${SERVER[@]}
          parallel scp /tmp/kemono-games-search-global/docker-compose.yml {}.jp.internal.abo.network:/root/kemono-games-search/ ::: ${SERVER[@]}
          parallel "ssh {}.jp.internal.abo.network 'cd /root/kemono-games-search && docker compose up -d'" ::: ${SERVER[@]}

  deploy-cn:
    needs: [push]
    runs-on: [self-hosted, home]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy CN
        run: |
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          cp docker-compose.cn.sample.yml /tmp/docker-compose.yml
          sed -i "s/{{GIT-SHA}}/${GIT_HASH}/g" /tmp/docker-compose.yml
          scp /tmp/docker-compose.yml web02.internal.abo.network:/root/kemono-games-search/
          ssh web02.internal.abo.network "cd /root/kemono-games-search && docker compose up -d"